# permissions for end users to edit sampleoperands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleoperand-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - sampleoperands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - sampleoperands/status
  verbs:
  - get
