# permissions for end users to view sampleoperands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleoperand-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - sampleoperands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - sampleoperands/status
  verbs:
  - get
