apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sample-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SampleOperand is the Schema for the sampleoperands API
      displayName: Sample Operand
      kind: SampleOperand
      name: sampleoperands.cache.example.com
      version: v1alpha1
  description: sampleoperator
  displayName: sampleoperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app=database
  links:
  - name: Sample Operator
    url: https://sample-operator.domain
  maturity: alpha
  provider:
    name: jeffmccormick
  version: 0.0.0
